### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by lluixhi** [facebook/luaffifb#19]
I would like to create a Gentoo Package for this lua library, and though there haven't been any (public) commits in months, it would be nice if there were some kind of released version.

Is this package ready for prime time?

**Comment by colesbury** [comment]
We just use the luaffi-scm-1.rockspec, because we primarily use it with Torch through [torch/distro](https://github.com/torch/distro). I can make a version number if that helps.

I'm not aware of any major bugs, with the following caveats:

1. The parser is not perfect. There might be a few cases like #8, but it generally is pretty robust.
2. We could use native 64-bit ints in a few more places (#12)
3. We don't free the JIT-ed callback functions on exit because the ordering of Lua unloading libraries can lead to crashes (https://github.com/facebook/luaffifb/blob/master/ffi.c#L1448). This is only an issue if you're creating lots of lua_States.
